### ISSUE TITLE
How to assess the benign answering rate?

### ISSUE THREAD

**Issue by zichuan-liu** [AAAAAAsuka/llm_defends#1]
Hi, i like your paper and it's same to <[SmoothLLM: Defending LLMs Against Jailbreaking Attacks](https://arxiv.org/abs/2310.03684)>, I'd like to know how you're evaluating the BAR, I don't seem to see it in the code, THX!

**Comment by AAAAAAsuka** [comment]
RA-LLM has no difference in processing methods for normal input and malicious input. You can find more details by check our paper. In addition, our paper was published earlier than SmoothLLM，thanks.

**Comment by zichuan-liu** [comment]
Thanks for your quick reply! BAR can only assess whether a response is benign or not, but if a random injection changes the semantics, LLMs of whether the response will be different from before.

**Comment by AAAAAAsuka** [comment]
Thank you for your valuable comment.

In fact, we never claimed that "BAR can only assess whether a response is benign or not", we assessed the answering rate of RA-LLM to benign input. The letter "A" in "BAR" is an abbreviation for answering, which you can find explained in Section 4.2 of the paper.

Secondly, when RA-LLM determines that an input is benign, RA-LLM will take the response of the original input as the final response output, instead of the response of the random dropped input, which ensures that RA-LLM has no performance loss for the majority of benign inputs. You can see this clearly in Equation 3 in Section 3.2 of the paper.

Finally, in case you're interested, considering the misclassification of benign inputs due to random drop in the Monte Carlo process, we propose to use the hyperparameter $t$ to adjust the tolerance level of misclassification. You can find a discussion of this in the '''The Practical Choice of t''' section of Section 3.3 of the paper

thanks,
Bochuan
